# Generated by Django 4.0.4 on 2022-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=256)),
                ('jobDescription', models.CharField(max_length=500)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
