# Generated by Django 4.0.4 on 2022-06-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_num', models.CharField(max_length=14)),
                ('authorized_service_center_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=256)),
                ('jobDescription', models.CharField(max_length=500)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('UpdatedTime', models.DateTimeField(auto_now=True)),
                ('jobStatus', models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=20)),
                ('customerName', models.CharField(max_length=256, null=True)),
                ('customerAddress', models.CharField(max_length=500, null=True)),
                ('customerMobileNumber', models.CharField(max_length=10, null=True)),
                ('EstimatedCompletionDate', models.DateField(default=None, null=True)),
                ('device_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet')], default='Mobile', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('imei_num1', models.CharField(blank=True, max_length=15, null=True)),
                ('imei_num2', models.CharField(blank=True, max_length=15, null=True)),
                ('part_code', models.CharField(blank=True, max_length=25, null=True)),
                ('part_replacement_warranty', models.CharField(choices=[('In Warranty', 'In Warranty'), ('Out Warranty', 'Out warranty')], default='Out Warranty', max_length=20)),
                ('purchased_from', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_status', models.CharField(choices=[('In Warranty', 'In Warranty'), ('Out Warranty', 'Out warranty'), ('Return Warranty', 'Return warranty'), ('No Warranty', 'No warranty')], default='No Warranty', max_length=20)),
                ('condition_of_set', models.CharField(choices=[('Physical Damage', 'Physical Damage'), ('Water Damage', 'Water Damage'), ('Good Condition', 'Good Condition')], default='Good Condition', max_length=20)),
                ('accessories_sbumitted', models.CharField(blank=True, max_length=500, null=True)),
                ('EstimatedCost', models.FloatField(blank=True, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='media')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job')),
            ],
        ),
    ]
