# Generated by Django 4.0.4 on 2022-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobStatus',
            field=models.CharField(choices=[('RG', 'Registered'), ('IP', 'In Progress'), ('CL', 'Closed'), ('DL', 'Delivered')], default='RG', max_length=2),
        ),
    ]
