# Generated by Django 4.0.4 on 2022-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='authorized_service_center_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='contact_num',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
