# Generated by Django 4.0.4 on 2022-06-25 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_serviceprovider_authorized_service_center_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
