# Generated by Django 4.0.4 on 2022-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_job_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='EstimatedCompletionDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customerAddress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customerMobileNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customerName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
