# Generated by Django 4.0.4 on 2022-04-16 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_job_estimatedcompletiondate_job_customeraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobReferenceNumber',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
