# Generated by Django 4.0.4 on 2022-04-16 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_job_jobreferencenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='customerName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobReferenceNumber',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
