# Generated by Django 4.0.4 on 2022-05-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_num', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Handset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('imei_num1', models.CharField(blank=True, max_length=15, null=True)),
                ('imei_num2', models.CharField(blank=True, max_length=15, null=True)),
                ('pop_date', models.DateField(blank=True, null=True)),
                ('purchased_from', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_status', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_of_set', models.CharField(blank=True, max_length=100, null=True)),
                ('accessories_sbumitted', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
