# Generated by Django 4.0.4 on 2022-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_job_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobReferenceNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
