# Generated by Django 4.0.4 on 2022-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_job_jobreferencenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASC',
        ),
        migrations.DeleteModel(
            name='Handset',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobReferenceNumber',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='created',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='updated',
        ),
        migrations.AddField(
            model_name='job',
            name='UpdatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='accessories_sbumitted',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='condition_of_set',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='imei_num1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='imei_num2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='warranty_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_num',
            field=models.CharField(default='NA', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
