# Generated by Django 4.0.4 on 2022-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_history_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='username',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
    ]
