# Generated by Django 4.0.4 on 2022-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_serviceprovider_password_serviceprovider_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='device_type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet')], default='Mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='condition_of_set',
            field=models.CharField(choices=[('Physical Damage', 'Physical Damage'), ('Water Damage', 'Water Damage'), ('Good Condition', 'Good Condition')], default='Good Condition', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='warranty_status',
            field=models.CharField(choices=[('In Warranty', 'In Warranty'), ('Out Warranty', 'Out warranty'), ('Return Warranty', 'Return warranty'), ('No Warranty', 'No warranty')], default='No Warranty', max_length=20),
        ),
    ]
