# Generated by Django 4.0.4 on 2022-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_job_brand_job_device_type_alter_job_condition_of_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pop_date',
        ),
        migrations.AddField(
            model_name='job',
            name='part_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='part_replacement_warranty',
            field=models.CharField(choices=[('In Warranty', 'In Warranty'), ('Out Warranty', 'Out warranty')], default='Out Warranty', max_length=20),
        ),
    ]
