# Generated by Django 4.0.4 on 2022-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_name_serviceprovider_authorized_service_center_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
