# Generated by Django 4.0.4 on 2022-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_job_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
