# Generated by Django 4.0.4 on 2022-06-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_serviceprovider_user'),
        ('home', '0021_alter_job_id'),
    ]

    operations = [
    ]
