# Generated by Django 4.0.4 on 2022-06-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20220625_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
