# Generated by Django 3.2.18 on 2023-05-01 08:31

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='EstimatedCompletionDate',
            field=models.DateField(default=None, null=True, validators=[home.models.only_futuredate]),
        ),
    ]
